# base_url = "http://localhost:8080"
title = "日語道"
description = "日語道 - Japanese with Elliott"
default_language = "en"
compile_sass = true
minify_html = true

[markdown]
highlight_code = true

[[taxonomies]]
name = "tags"
feed = true

[extra]
author = "Elliott Ashby"
github = "Aethar01"
